name = "rss-worker"
main = "src/worker.js"
node_compat = true
compatibility_date = "2025-10-03"
compatibility_flags = [ "nodejs_compat" ]

# [build]
# command = "npm run build"
# cwd = "dist"
# watch_dir = "dist"
